CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    ticket_id INT,
    user_id INT,
    qty INT,
    total INTEGER,
    status VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_by VARCHAR(255),
    FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);