BEGIN;
CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    type text,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

);

COMMIT;